// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configs.proto

/*
Package entity is a generated protocol buffer package.

It is generated from these files:
	configs.proto
	dynamic_info.proto
	news.proto
	news_group.proto
	user.proto

It has these top-level messages:
	DynamicInfo
	News
	NewsGroup
	User
*/
package entity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PLATFORM int32

const (
	PLATFORM_PHONE    PLATFORM = 10000
	PLATFORM_QQ       PLATFORM = 10001
	PLATFORM_WEIXIN   PLATFORM = 10002
	PLATFORM_WEIBO    PLATFORM = 10003
	PLATFORM_FACEBOOK PLATFORM = 10004
	PLATFORM_INS      PLATFORM = 10005
	PLATFORM_TWITTER  PLATFORM = 10006
)

var PLATFORM_name = map[int32]string{
	10000: "PHONE",
	10001: "QQ",
	10002: "WEIXIN",
	10003: "WEIBO",
	10004: "FACEBOOK",
	10005: "INS",
	10006: "TWITTER",
}
var PLATFORM_value = map[string]int32{
	"PHONE":    10000,
	"QQ":       10001,
	"WEIXIN":   10002,
	"WEIBO":    10003,
	"FACEBOOK": 10004,
	"INS":      10005,
	"TWITTER":  10006,
}

func (x PLATFORM) Enum() *PLATFORM {
	p := new(PLATFORM)
	*p = x
	return p
}
func (x PLATFORM) String() string {
	return proto.EnumName(PLATFORM_name, int32(x))
}
func (x *PLATFORM) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PLATFORM_value, data, "PLATFORM")
	if err != nil {
		return err
	}
	*x = PLATFORM(value)
	return nil
}
func (PLATFORM) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

type FLAG int32

const (
	FLAG_FLAG_NO_IMAGE  FLAG = 20000
	FLAG_FLAG_ONE_IMAGE FLAG = 20001
	FLAG_FLAG_GELLAY    FLAG = 20002
	FLAG_FLAG_VIDEO     FLAG = 20003
	FLAG_FLAG_LIVE      FLAG = 20004
	FLAG_FLAG_LINK      FLAG = 20005
	FLAG_FLAG_FULL_LINK FLAG = 20006
	FLAG_FLAG_SUBJECT   FLAG = 20007
	FLAG_FLAG_EVENT     FLAG = 20008
)

var FLAG_name = map[int32]string{
	20000: "FLAG_NO_IMAGE",
	20001: "FLAG_ONE_IMAGE",
	20002: "FLAG_GELLAY",
	20003: "FLAG_VIDEO",
	20004: "FLAG_LIVE",
	20005: "FLAG_LINK",
	20006: "FLAG_FULL_LINK",
	20007: "FLAG_SUBJECT",
	20008: "FLAG_EVENT",
}
var FLAG_value = map[string]int32{
	"FLAG_NO_IMAGE":  20000,
	"FLAG_ONE_IMAGE": 20001,
	"FLAG_GELLAY":    20002,
	"FLAG_VIDEO":     20003,
	"FLAG_LIVE":      20004,
	"FLAG_LINK":      20005,
	"FLAG_FULL_LINK": 20006,
	"FLAG_SUBJECT":   20007,
	"FLAG_EVENT":     20008,
}

func (x FLAG) Enum() *FLAG {
	p := new(FLAG)
	*p = x
	return p
}
func (x FLAG) String() string {
	return proto.EnumName(FLAG_name, int32(x))
}
func (x *FLAG) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FLAG_value, data, "FLAG")
	if err != nil {
		return err
	}
	*x = FLAG(value)
	return nil
}
func (FLAG) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

type KIND int32

const (
	KIND_KIND_NO_IMAGE  KIND = 30000
	KIND_KIND_ONE_IMAGE KIND = 30001
	KIND_KIND_GELLAY    KIND = 30002
	KIND_KIND_VIDEO     KIND = 30003
	KIND_KIND_LIVE      KIND = 30004
	KIND_KIND_LINK      KIND = 30005
	KIND_KIND_FULL_LINK KIND = 30006
	KIND_KIND_SUBJECT   KIND = 30007
	KIND_KIND_EVENT     KIND = 30008
)

var KIND_name = map[int32]string{
	30000: "KIND_NO_IMAGE",
	30001: "KIND_ONE_IMAGE",
	30002: "KIND_GELLAY",
	30003: "KIND_VIDEO",
	30004: "KIND_LIVE",
	30005: "KIND_LINK",
	30006: "KIND_FULL_LINK",
	30007: "KIND_SUBJECT",
	30008: "KIND_EVENT",
}
var KIND_value = map[string]int32{
	"KIND_NO_IMAGE":  30000,
	"KIND_ONE_IMAGE": 30001,
	"KIND_GELLAY":    30002,
	"KIND_VIDEO":     30003,
	"KIND_LIVE":      30004,
	"KIND_LINK":      30005,
	"KIND_FULL_LINK": 30006,
	"KIND_SUBJECT":   30007,
	"KIND_EVENT":     30008,
}

func (x KIND) Enum() *KIND {
	p := new(KIND)
	*p = x
	return p
}
func (x KIND) String() string {
	return proto.EnumName(KIND_name, int32(x))
}
func (x *KIND) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(KIND_value, data, "KIND")
	if err != nil {
		return err
	}
	*x = KIND(value)
	return nil
}
func (KIND) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

func init() {
	proto.RegisterEnum("entity.PLATFORM", PLATFORM_name, PLATFORM_value)
	proto.RegisterEnum("entity.FLAG", FLAG_name, FLAG_value)
	proto.RegisterEnum("entity.KIND", KIND_name, KIND_value)
}

func init() {
	proto.RegisterFile("configs.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xce, 0xc9, 0x4e, 0x2a, 0x51,
	0x10, 0xc6, 0xf1, 0x9c, 0x3b, 0x00, 0xb7, 0x80, 0x6b, 0x59, 0xfa, 0x14, 0x2c, 0x7c, 0x87, 0x06,
	0x4e, 0xe3, 0xb1, 0x0f, 0x75, 0x18, 0x1a, 0xd0, 0x15, 0x0b, 0xa3, 0x86, 0x0d, 0x18, 0x65, 0xe3,
	0x5b, 0x38, 0xaf, 0x7a, 0xe1, 0xac, 0x4b, 0x07, 0x1c, 0x9e, 0xa9, 0x9f, 0xc2, 0x74, 0x81, 0xa1,
	0x59, 0x55, 0xf2, 0x4b, 0xe5, 0xcb, 0x1f, 0x8a, 0xdb, 0xa3, 0xe1, 0xee, 0x60, 0xef, 0x70, 0x6d,
	0xff, 0x60, 0x34, 0x1e, 0x51, 0x66, 0x67, 0x38, 0x1e, 0x8c, 0x8f, 0x4a, 0x7d, 0xc8, 0x35, 0xac,
	0x17, 0xfa, 0xae, 0x55, 0x27, 0x80, 0xbf, 0x8d, 0x75, 0xc7, 0x1a, 0x8f, 0x99, 0xb2, 0xf0, 0xab,
	0xd9, 0xc4, 0x13, 0xa6, 0x3c, 0x64, 0x7a, 0xda, 0x6c, 0x1a, 0xc6, 0x53, 0x4e, 0x3e, 0x7a, 0xda,
	0x94, 0x1d, 0x9e, 0x31, 0x15, 0x21, 0xe7, 0x7b, 0x15, 0x5d, 0x76, 0x2e, 0xc0, 0x73, 0xa6, 0x1c,
	0xfc, 0x36, 0xdc, 0xc6, 0x0b, 0xa6, 0x02, 0x64, 0xc3, 0x9e, 0x09, 0x43, 0xdd, 0xc2, 0x4b, 0x2e,
	0x4d, 0x14, 0xfc, 0xf1, 0xad, 0x57, 0xa3, 0x15, 0x28, 0x26, 0xb7, 0xcf, 0xae, 0x6f, 0xea, 0x5e,
	0x4d, 0xe3, 0x55, 0xa4, 0x68, 0x15, 0xfe, 0x0b, 0x3a, 0xd6, 0x33, 0xbd, 0x8e, 0x14, 0x2d, 0x43,
	0x5e, 0xb4, 0xa6, 0xad, 0xf5, 0xb6, 0xf0, 0x26, 0x52, 0x84, 0x00, 0x42, 0x5d, 0x53, 0xd5, 0x0e,
	0x6f, 0x23, 0x45, 0x4b, 0xf0, 0x4f, 0xc4, 0x9a, 0xae, 0xc6, 0xbb, 0x05, 0xe0, 0x00, 0xef, 0x53,
	0xe3, 0x7e, 0xc7, 0xda, 0xa9, 0x3e, 0x44, 0x8a, 0x08, 0x0a, 0xa2, 0xed, 0x4e, 0x79, 0x43, 0x57,
	0x42, 0x7c, 0x4c, 0xad, 0xeb, 0xae, 0xe6, 0x10, 0x9f, 0x22, 0x25, 0xd9, 0x81, 0xe1, 0x6a, 0x92,
	0x9d, 0xdc, 0x79, 0xf6, 0x73, 0x2c, 0xcb, 0x82, 0xf3, 0xec, 0x97, 0x58, 0xb2, 0x45, 0x67, 0xd9,
	0xaf, 0xb1, 0x0c, 0x0b, 0x4d, 0xb3, 0xdf, 0x62, 0xa9, 0x14, 0x91, 0xec, 0xc9, 0x02, 0x70, 0x80,
	0xef, 0xa9, 0xf1, 0x79, 0xf6, 0x47, 0x2c, 0xd9, 0xa2, 0x3f, 0xd9, 0x9f, 0xa9, 0xf5, 0x69, 0xf6,
	0x57, 0xac, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xff, 0x42, 0xc6, 0xe6, 0x01, 0x00, 0x00,
}
