// Code generated by protoc-gen-go.
// source: protobuf/news.proto
// DO NOT EDIT!

/*
Package entity is a generated protocol buffer package.

It is generated from these files:
	protobuf/news.proto
	protobuf/user.proto

It has these top-level messages:
	News
	User
*/
package protobuf

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type News struct {
	Id               *int64               `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Title            *string              `protobuf:"bytes,2,req,name=title" json:"title,omitempty"`
	Content          *string              `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	Image            *string              `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Desc             *string              `protobuf:"bytes,5,opt,name=desc" json:"desc,omitempty"`
	Relativenews     []*News_RelativeNews `protobuf:"group,6,rep,name=RelativeNews,json=relativenews" json:"relativenews,omitempty"`
	Flag             *int32               `protobuf:"varint,7,req,name=flag" json:"flag,omitempty"`
	Kind             *int32               `protobuf:"varint,8,req,name=kind" json:"kind,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *News) Reset()                    { *m = News{} }
func (m *News) String() string            { return proto.CompactTextString(m) }
func (*News) ProtoMessage()               {}
func (*News) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *News) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *News) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *News) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *News) GetImage() string {
	if m != nil && m.Image != nil {
		return *m.Image
	}
	return ""
}

func (m *News) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *News) GetRelativenews() []*News_RelativeNews {
	if m != nil {
		return m.Relativenews
	}
	return nil
}

func (m *News) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *News) GetKind() int32 {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return 0
}

type News_RelativeNews struct {
	Id               *int64  `protobuf:"varint,11,req,name=id" json:"id,omitempty"`
	Title            *string `protobuf:"bytes,12,req,name=title" json:"title,omitempty"`
	Image            *string `protobuf:"bytes,13,opt,name=image" json:"image,omitempty"`
	Desc             *string `protobuf:"bytes,14,opt,name=desc" json:"desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *News_RelativeNews) Reset()                    { *m = News_RelativeNews{} }
func (m *News_RelativeNews) String() string            { return proto.CompactTextString(m) }
func (*News_RelativeNews) ProtoMessage()               {}
func (*News_RelativeNews) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *News_RelativeNews) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *News_RelativeNews) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *News_RelativeNews) GetImage() string {
	if m != nil && m.Image != nil {
		return *m.Image
	}
	return ""
}

func (m *News_RelativeNews) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*News)(nil), "entity.News")
	proto.RegisterType((*News_RelativeNews)(nil), "entity.News.RelativeNews")
}

func init() { proto.RegisterFile("protobuf/news.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x31, 0x4e, 0xc4, 0x30,
	0x10, 0x45, 0xb5, 0x4e, 0xb2, 0x0b, 0x43, 0xd8, 0xc2, 0x50, 0x0c, 0x54, 0x16, 0x95, 0x2b, 0x23,
	0xd1, 0x73, 0x05, 0x0a, 0x1f, 0x00, 0x29, 0xac, 0x67, 0x57, 0x16, 0xc1, 0x41, 0xc9, 0x40, 0xc4,
	0xc9, 0xb8, 0x1e, 0x1a, 0x27, 0x40, 0x10, 0xdb, 0xcd, 0xfb, 0xfa, 0x1a, 0xfd, 0x07, 0x17, 0xaf,
	0x7d, 0xc7, 0xdd, 0xd3, 0xdb, 0xfe, 0x36, 0xd1, 0x38, 0xb8, 0x4c, 0x7a, 0x4d, 0x89, 0x23, 0x7f,
	0xdc, 0x7c, 0x2a, 0x28, 0x1f, 0x68, 0x1c, 0xf4, 0x16, 0x54, 0x0c, 0xb8, 0x32, 0xca, 0x16, 0x5e,
	0xc5, 0xa0, 0x2f, 0xa1, 0xe2, 0xc8, 0x2d, 0xa1, 0x32, 0xca, 0x9e, 0xfa, 0x09, 0x34, 0xc2, 0x66,
	0xd7, 0x25, 0xa6, 0xc4, 0x58, 0xe4, 0xfc, 0x1b, 0xa5, 0x1f, 0x5f, 0x9a, 0x03, 0x61, 0x69, 0x56,
	0xd2, 0xcf, 0xa0, 0x35, 0x94, 0x81, 0x86, 0x1d, 0x56, 0x39, 0xcc, 0xb7, 0xbe, 0x87, 0xba, 0xa7,
	0xb6, 0xe1, 0xf8, 0x4e, 0x32, 0x08, 0xd7, 0xa6, 0xb0, 0x70, 0x77, 0xe5, 0xa6, 0x45, 0x4e, 0xd6,
	0x38, 0x3f, 0x17, 0x04, 0xfc, 0x9f, 0xba, 0xbc, 0xdc, 0xb7, 0xcd, 0x01, 0x37, 0x46, 0xd9, 0xca,
	0xe7, 0x5b, 0xb2, 0xe7, 0x98, 0x02, 0x9e, 0x4c, 0x99, 0xdc, 0xd7, 0x8f, 0x50, 0x2f, 0xbf, 0xcc,
	0x82, 0x67, 0xff, 0x05, 0xeb, 0xa5, 0xe0, 0x8f, 0xc6, 0xf9, 0x31, 0x8d, 0xed, 0xaf, 0xc6, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x50, 0x6f, 0x84, 0x57, 0x01, 0x00, 0x00,
}
