// Code generated by protoc-gen-go.
// source: protobuf/user.proto
// DO NOT EDIT!

package protobuf

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FOO int32

const (
	FOO_X FOO = 17
)

var FOO_name = map[int32]string{
	17: "X",
}
var FOO_value = map[string]int32{
	"X": 17,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}
func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}
func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}
func (FOO) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type User struct {
	Id               *int64   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Gender           *int32   `protobuf:"varint,3,req,name=gender" json:"gender,omitempty"`
	Desc             *string  `protobuf:"bytes,4,opt,name=desc" json:"desc,omitempty"`
	Degree           *float32 `protobuf:"fixed32,5,opt,name=degree" json:"degree,omitempty"`
	Flags            []int32  `protobuf:"varint,6,rep,name=flags" json:"flags,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *User) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *User) GetGender() int32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *User) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *User) GetDegree() float32 {
	if m != nil && m.Degree != nil {
		return *m.Degree
	}
	return 0
}

func (m *User) GetFlags() []int32 {
	if m != nil {
		return m.Flags
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "entity.User")
	proto.RegisterEnum("entity.FOO", FOO_name, FOO_value)
}

func init() { proto.RegisterFile("protobuf/user.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xca, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x80, 0x61, 0x72, 0x69, 0x0a, 0x1e, 0x22, 0x7a, 0x8a, 0x64, 0x0c, 0x4e, 0xc1, 0x41, 0xdf,
	0xc2, 0xb5, 0x10, 0x10, 0x5c, 0xab, 0xb9, 0x96, 0x82, 0xb6, 0x92, 0xa4, 0x83, 0xbb, 0x0f, 0x2e,
	0xa9, 0xdd, 0xfe, 0x0f, 0x7e, 0xdc, 0xbe, 0xc3, 0x90, 0x86, 0xfb, 0xd8, 0x9c, 0xc7, 0xc8, 0xe1,
	0x34, 0x89, 0x4a, 0xee, 0x53, 0x97, 0x3e, 0x87, 0xaf, 0xc0, 0xe2, 0x1a, 0x39, 0xd0, 0x0a, 0xa1,
	0xf3, 0x5a, 0x18, 0xb0, 0xd2, 0x41, 0xe7, 0x89, 0xb0, 0xe8, 0xeb, 0x17, 0x6b, 0x30, 0x60, 0x17,
	0x6e, 0x6a, 0xda, 0x63, 0xd9, 0x72, 0xef, 0x39, 0x68, 0x69, 0xc0, 0x2a, 0x37, 0x2b, 0xbf, 0x9e,
	0xe3, 0x43, 0x17, 0x46, 0xe4, 0x37, 0x77, 0x7e, 0x3d, 0xb7, 0x81, 0x59, 0x2b, 0x23, 0x2c, 0xb8,
	0x59, 0xb4, 0x43, 0xd5, 0x3c, 0xeb, 0x36, 0xea, 0xd2, 0x48, 0xab, 0xdc, 0x1f, 0xc7, 0x25, 0xca,
	0x4b, 0x55, 0x91, 0x42, 0x71, 0x5b, 0x6f, 0x7e, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xf4, 0x0d,
	0xd4, 0xb2, 0x00, 0x00, 0x00,
}
